#!/usr/bin/env python3
"""
Docker Deployment for Local LLMs.

Complete Docker setup for deploying models with API server.

Usage:
    # Generate Dockerfile and docker-compose.yml
    python deployment/docker_setup.py --model ./phi3-mini-q4_k_m.gguf --port 8080

    # Build and run
    docker-compose up -d
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Optional


class DockerSetup:
    """
    Docker deployment setup.

    Features:
    - Dockerfile generation
    - docker-compose.yml generation
    - Health checks
    - Volume mounting
    - GPU support
    - Multi-stage builds
    """

    def __init__(self, output_dir: str = "./docker"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_dockerfile(
        self,
        model_path: str,
        port: int = 8080,
        gpu: bool = False,
        python_version: str = "3.11",
    ) -> Path:
        """
        Generate Dockerfile.

        Args:
            model_path: Path to model file
            port: Port to expose
            gpu: Enable GPU support
            python_version: Python version

        Returns:
            Path to generated Dockerfile
        """
        if gpu:
            base_image = f"nvidia/cuda:12.2.0-runtime-ubuntu22.04"
            install_cuda = """
RUN apt-get update && apt-get install -y \\
    build-essential \\
    cmake \\
    git \\
    && rm -rf /var/lib/apt/lists/*

RUN pip install llama-cpp-python[cuda]
"""
        else:
            base_image = f"python:{python_version}-slim"
            install_cuda = """
RUN apt-get update && apt-get install -y \\
    build-essential \\
    cmake \\
    git \\
    && rm -rf /var/lib/apt/lists/*

RUN pip install llama-cpp-python
"""

        dockerfile_content = f"""# Multi-stage build for {model_path}
# Generated by DockerSetup

# Stage 1: Build
FROM {base_image} as builder

WORKDIR /app

{install_cuda}

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Stage 2: Runtime
FROM {base_image} as runtime

WORKDIR /app

# Install runtime dependencies
RUN apt-get update && apt-get install -y \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Copy from builder
COPY --from=builder /usr/local/lib/python{python_version}/site-packages /usr/local/lib/python{python_version}/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /app /app

# Copy model
COPY {model_path} /app/model/

# Expose port
EXPOSE {port}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:{port}/health || exit 1

# Run server
CMD ["python", "inference/llama_server.py", "--model", "/app/model/{Path(model_path).name}", "--host", "0.0.0.0", "--port", "{port}"]
"""

        dockerfile_path = self.output_dir / "Dockerfile"
        dockerfile_path.write_text(dockerfile_content)

        print(f"Dockerfile generated: {dockerfile_path}")
        return dockerfile_path

    def generate_docker_compose(
        self,
        model_path: str,
        port: int = 8080,
        gpu: bool = False,
        volumes: Optional[list[str]] = None,
    ) -> Path:
        """
        Generate docker-compose.yml.

        Args:
            model_path: Path to model file
            port: Port to expose
            gpu: Enable GPU support
            volumes: Additional volumes

        Returns:
            Path to generated docker-compose.yml
        """
        gpu_config = ""
        if gpu:
            gpu_config = """
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]"""

        volumes_config = ""
        if volumes:
            for vol in volumes:
                volumes_config += f"      - {vol}\n"

        compose_content = f"""version: '3.8'

services:
  llm-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: phi3-mini-server
    ports:
      - "{port}:{port}"{gpu_config}
    volumes:
      - ../models:/app/model{volumes_config}
    environment:
      - MODEL_PATH=/app/model/{Path(model_path).name}
      - N_CTX=4096
      - N_THREADS=4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - llm-server

  # Optional: Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
"""

        compose_path = self.output_dir / "docker-compose.yml"
        compose_path.write_text(compose_content)

        print(f"docker-compose.yml generated: {compose_path}")
        return compose_path

    def generate_prometheus_config(self) -> Path:
        """Generate Prometheus configuration."""
        prometheus_content = """global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'llm-server'
    static_configs:
      - targets: ['llm-server:8080']
    metrics_path: '/metrics'
"""

        prometheus_path = self.output_dir / "prometheus.yml"
        prometheus_path.write_text(prometheus_content)

        print(f"prometheus.yml generated: {prometheus_path}")
        return prometheus_path

    def generate_nginx_config(self, port: int = 8080) -> Path:
        """Generate Nginx reverse proxy config."""
        nginx_content = f"""upstream llm_server {{
    server llm-server:{port};
}}

server {{
    listen 80;
    server_name localhost;

    location / {{
        proxy_pass http://llm_server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }}

    location /health {{
        proxy_pass http://llm_server/health;
    }}
}}
"""

        nginx_path = self.output_dir / "nginx.conf"
        nginx_path.write_text(nginx_content)

        print(f"nginx.conf generated: {nginx_path}")
        return nginx_path

    def generate_all(
        self,
        model_path: str,
        port: int = 8080,
        gpu: bool = False,
    ) -> dict:
        """
        Generate all Docker deployment files.

        Args:
            model_path: Path to model file
            port: Port to expose
            gpu: Enable GPU support

        Returns:
            Dictionary of generated file paths
        """
        print(f"\nGenerating Docker deployment files...")
        print(f"  Model: {model_path}")
        print(f"  Port: {port}")
        print(f"  GPU: {gpu}")

        files = {
            "dockerfile": self.generate_dockerfile(model_path, port, gpu),
            "docker_compose": self.generate_docker_compose(model_path, port, gpu),
            "prometheus": self.generate_prometheus_config(),
            "nginx": self.generate_nginx_config(port),
        }

        print(f"\nAll files generated in: {self.output_dir}")
        print(f"\nTo deploy:")
        print(f"  cd {self.output_dir}")
        print(f"  docker-compose up -d")

        return files


def main(argv=None):
    """Generate Docker deployment files for a real model path."""
    parser = argparse.ArgumentParser(description="Generate Docker deployment files")
    parser.add_argument("--model", required=True, help="Path to model file")
    parser.add_argument("--port", type=int, default=8080, help="Port to expose")
    parser.add_argument("--gpu", action="store_true", help="Enable GPU support")
    parser.add_argument(
        "--only",
        choices=["dockerfile", "compose", "prometheus", "nginx", "all"],
        default="all",
        help="Which files to generate",
    )
    parser.add_argument("--output", default="./docker", help="Output directory")

    args = parser.parse_args(argv)

    try:
        setup = DockerSetup(output_dir=args.output)

        if args.only == "dockerfile":
            setup.generate_dockerfile(args.model, args.port, args.gpu)
        elif args.only == "compose":
            setup.generate_docker_compose(args.model, args.port, args.gpu)
        elif args.only == "prometheus":
            setup.generate_prometheus_config()
        elif args.only == "nginx":
            setup.generate_nginx_config(args.port)
        else:
            setup.generate_all(args.model, args.port, args.gpu)

        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
